spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: tlsdPcks05@
    url: jdbc:mysql://127.0.0.1:3306/database
    username: root
#      datasource:
#      url:jdbc:h2:tcp://localhost/~/subdb;MVCC=TRUE
#      username: sa
  #    password:
#      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
value:
  request_value:
    api_key: 059980d47126472a865a1fced65d1948
    event_type: acc
    get_type: json
    min_y: 33.643
    max_y: 38.364
    min_x: 124.3636
    max_x: 130.9198
    type: all
    url: https://openapi.its.go.kr:9443/eventInfo
logging:
  level:
    sql: debug